### ISSUE TITLE
Published to npm as ES6, can you do ES5?

### ISSUE THREAD

**Issue by avindra** [elazzabi/fuzzy-string-matching#1]
Hi,

Any chance you can publish this to npm as ES5?

I pulled this into my project and our entire build process broke (Webpack) because we exclude babel transformations for files under `node_modules` in our project.

**Comment by avindra** [comment]
For others with the same issue, you can workaround it by telling Webpack to babelify these modules:

```
-                exclude : /(?:node_modules)/,
+                exclude : /(?:node_modules)\/(?!(fuzzy-string-matching|longest-common-subsequence))/,
```

**Comment by elazzabi** [comment]
I'm working on it to fix the issue
Sorry for inconvenience

**Comment by elazzabi** [comment]
Done. Can you test after updating the module?

**Comment by avindra** [comment]
Thanks for the quick turnaround @elazzabi. I'll test the new version when I go into the office on Monday :+1:

**Comment by avindra** [comment]
Works fine now. Thanks man

**Comment by elazzabi** [comment]
You are welcome :smile_cat:
